"""Shared protocol for Texas engine adapters."""

from typing import Any, Dict, Optional, Protocol


class TexasEngineProtocol(Protocol):
    backend_name: str
    phase: Any
    players: Dict[str, Any]
    player_order: list[str]
    current_player_sid: Optional[str]
    current_bet: int
    last_raise_amount: int
    community_cards: list[Any]
    chat_history: list[Any]
    hand_number: int
    turn_started_at: Any

    CHAT_ALLOWED_PHASES: set[Any]

    def add_player(self, sid: str, player_id: str, nickname: str, buy_in: int) -> bool: ...
    def remove_player(self, sid: str) -> bool: ...
    def can_start(self) -> bool: ...
    def start_hand(self) -> Dict[str, Any]: ...
    def process_move(self, sid: str, action: str, **kwargs) -> Dict[str, Any]: ...
    def get_game_state(self, sid: Optional[str], for_spectator: bool = False, reveal_all: bool = False) -> Dict[str, Any]: ...
    def get_total_pot(self) -> int: ...
    def cards_to_strings(self, cards: list[Any]) -> list[str]: ...
    def get_turn_time_remaining(self) -> int: ...
    def is_hand_over(self) -> bool: ...
    def handle_timeout(self, sid: str) -> Dict[str, Any]: ...
    def advance_phase(self) -> Dict[str, Any]: ...
    def get_all_hole_cards(self) -> Dict[str, list[str]]: ...
    def to_dict(self) -> Dict[str, Any]: ...
